disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name

opt_in_rules:
  - empty_count
  - force_unwrapping

included:
  - ForavaApp
  - ForavaWatch
  - Shared

excluded:
  - Pods
  - Carthage

reporter: "xcode"
